### ISSUE TITLE
A Jupyter notebook with the example tutorial would be nice

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar#24]
The main reason for the notebook is so I can see the outputs as well as the inputs. Reading through the docs, it's hard to know exactly what is outputted (even though there is a text description of the output)

**Comment by computron** [comment]
(also should only take ~30 mins to prepare)

**Comment by computron** [comment]
(and also nice to be able to see the outputs since it might take time before someone gets their API key, this gives them something to look at in the meantime)

**Comment by AmalieT** [comment]
Added in 2011fb9d9a4853918c5d7da98134c7ccbdc5c782
