### ISSUE TITLE
docs should list endpoint as "http://api.matscholar.com" (or HTTPS when fixed)

### ISSUE THREAD

**Issue by computron** [materialsintelligence/matscholar#26]
just "api.matscholar.com" (as in the current docs) doesn't work for me - maybe related to https, I don't know

**Comment by jdagdelen** [comment]
Yes, this is the source of the error.

On Fri, May 31, 2019 at 6:34 PM, Anubhav Jain <notifications@github.com> wrote:
just "api.matscholar.com" (as in the current docs) doesn't work for me - maybe related to https, I don't know

**Comment by jdagdelen** [comment]
Ok, changed.
